"""Module demonstrating the use of Catalyst for in-situ visualization"""
##############################################################################
# A simple simulator for a 2D problem, with an in-situ coupling
# The data generation parameters for the vector field
# come from https://shaddenlab.berkeley.edu/uploads/LCS-tutorial/examples.html
# using Catalyst https://catalyst-in-situ.readthedocs.io/en/latest/index.html
#
# Author: Jean M. Favre, Swiss National Supercomputing Center
#
# this serial version runs until completion and saves images of the scalar field
# at regular intervals.
#
# run: python3 double_gyre_catalyst.py
#
# Tested with Python 3.14.0, Fri Jul 24 11:34:26 AM CEST 2026
#
##############################################################################
import math
import argparse
import numpy as np
import catalyst
import catalyst_conduit as conduit
import catalyst_conduit.blueprint
import matplotlib.pyplot as plt

class Simulation:
    """
    An animated vector field generated by a math expression

    Attributes
    ----------
    resolution : int, int
        the number of grid points on the I and J axis
    iterations : int
        the maximum number of iterations (default 100)
    """
    def __init__(self, resolution=(256,128), iterations=10):
        self.iteration = 0
        self.timestep = 0.1
        self.max_iterations = iterations

        self.xres = resolution[0] # X horizontal resolution
        self.yres = resolution[1] # Y vertical   resolution
        self.xaxis = np.linspace(0., 2., self.xres)
        self.yaxis = np.linspace(0., 1., self.yres)
        self.zaxis = np.linspace(0., 0., 1)
        
        self.vel_x = np.zeros(self.xres * self.yres, dtype=np.float64)
        self.vel_y = np.zeros(self.xres * self.yres, dtype=np.float64)
        self.vel_z = np.zeros(self.xres * self.yres, dtype=np.float64)
        self.A = 0.1 * np.pi
        self.w = 2.0 * np.pi / 10.
        self.E = 0.25
        
    def compute_onestep(self):
        At = self.E * np.sin(self.w * self.iteration * self.timestep)
        Bt = 1.0 - 2.0 * At
        for iy in range(self.yres):
          for ix in range(self.xres):
            Ft = (At * self.xaxis[ix] * self.xaxis[ix] + Bt * self.xaxis[ix]) * np.pi
            fft = 2.0 * At * self.xaxis[ix] + Bt
            self.vel_x[ix + iy*self.xres] = -self.A * np.sin(Ft) * np.cos(np.pi * self.yaxis[iy])
            self.vel_y[ix + iy*self.xres] =  self.A * np.cos(Ft) * np.sin(np.pi * self.yaxis[iy]) * fft
        
        self.iteration += 1

    def compute_loop(self):
        """Computes and updates velocity fields"""
        while self.iteration < self.max_iterations:
            self.compute_onestep()

    def draw_matplotlib(self):
        """Draw with mathplotlib"""
        x_coord, y_coord = np.meshgrid(self.xaxis, self.yaxis, indexing="xy")
        #plot the 'vel_x' field iso-contour lines
        fig, ax = plt.subplots()
        
        ax.set_xlim(self.xaxis[0], self.xaxis[-1])
        ax.set_ylim(self.yaxis[0], self.yaxis[-1])
        ax.set_aspect('equal', adjustable='box')
        CS = ax.contour(x_coord, y_coord, (self.vel_x*self.vel_x + self.vel_y*self.vel_y).reshape(self.yres,self.xres), levels=10)
        ax.clabel(CS, inline=True, fontsize=10)
        ax.set_title('Velocity magnitude iso-contours')
        plt.savefig(f'Velocitymagnitude.{self.iteration:03d}.png')
        #plot the velocity vectors sub-sampled
        fig1, ax1 = plt.subplots()
        ax1.set_xlim(self.xaxis[0], self.xaxis[-1])
        ax1.set_ylim(self.yaxis[0], self.yaxis[-1])
        ax1.set_aspect('equal', adjustable='box')
        stride = 10
        
        ax1.quiver(x_coord[::stride, ::stride], y_coord[::stride, ::stride],
                   self.vel_x.reshape(self.xres,self.yres)[::stride, ::stride], self.vel_y.reshape(self.xres,self.yres)[::stride, ::stride])
        ax1.set_title('Velocity vectors')
        plt.savefig(f'Velocity.{self.iteration:03d}.png')

class SimulationWithCatalyst(Simulation):
    """
    A specialized class to add in-situ visualization support

    Attributes
    ----------

    """
    def __init__(self, resolution=(256,128), iterations=10, pv_script="pvDoubleGyre.py"):
        Simulation.__init__(self, resolution, iterations)
        self.delta_x = 2.0 / (self.xres - 1)
        self.insitu = conduit.Node()
        self.pv_script = pv_script
        self.initialize_catalyst()
        
        self.exec_params = conduit.Node()
        
    def Initialize(self):
        channel = self.exec_params["catalyst/channels/grid"]
        channel["type"] = "mesh"
        mesh = channel["data"]
        meshType = "uniform"
        
        if meshType == "uniform":
            mesh["coordsets/coords/type"] = "uniform"
            mesh["coordsets/coords/dims/i"] = self.xres
            mesh["coordsets/coords/dims/j"] = self.yres
            mesh["coordsets/coords/dims/k"] = 1

            mesh["topologies/mesh/type"] = "uniform"
            mesh["topologies/mesh/coordset"] = "coords"

            mesh["coordsets/coords/origin/x"] = 0.0
            mesh["coordsets/coords/origin/y"] = 0.0
            mesh["coordsets/coords/origin/z"] = 0.0
            mesh["coordsets/coords/spacing/dx"] = self.delta_x
            mesh["coordsets/coords/spacing/dy"] = self.delta_x
            mesh["coordsets/coords/spacing/dz"] = self.delta_x
        elif meshType == "rectilinear":
            mesh["coordsets/coords/type"] = "rectilinear"
            mesh["coordsets/coords/values/x"].set_external(self.xaxis)
            mesh["coordsets/coords/values/y"].set_external(self.yaxis)
            mesh["topologies/mesh/type"] = "rectilinear"
            mesh["topologies/mesh/coordset"] = "coords"

        fields = mesh['fields']
        fields["/vel_x/association"] = "vertex"
        fields["/vel_x/topology"] = "mesh"
        fields["/vel_x/values"].set_external(self.vel_x)
        fields["/vel_x/volume_dependent"] = 'false'
        
        fields["vel_y/association"] = "vertex"
        fields["vel_y/topology"] = "mesh"
        fields["vel_y/values"].set_external(self.vel_y)
        fields["vel_y/volume_dependent"] = 'false'
        
        fields["Velocity/association"] = "vertex"
        fields["Velocity/topology"] = "mesh"
        fields["Velocity/values/x"].set_external(self.vel_x)
        fields["Velocity/values/y"].set_external(self.vel_y)
        fields["Velocity/values/z"].set_external(self.vel_z)

        # verify the mesh we created conforms to the blueprint
        verify_info = conduit.Node()
        if not conduit.blueprint.mesh.verify(mesh, verify_info):
          print("DoubleGyre Mesh Verify failed!")
          print(verify_info)
        else:
            pass
            #print("DoubleGyre Mesh verify success!")

    def compute_loop(self):
        """Computes and updates velocity fields"""
        while self.iteration < self.max_iterations:
            self.compute_onestep()
            state = self.exec_params["catalyst/state"]
            state["timestep"] = self.iteration
            state["time"] = self.iteration * 0.1
            catalyst.execute(self.exec_params)

    def initialize_catalyst(self):
        """Creates a Conduit node """
        self.insitu["catalyst/scripts/script/filename"] = self.pv_script
        self.insitu["catalyst_load/implementation"] = 'paraview'

        # open Catalyst
        catalyst.initialize(self.insitu)

    def finalize_catalyst(self):
        """close"""
        print("finalize_catalyst\n")
        print(self.exec_params["catalyst/channels/grid/data"])
        catalyst.finalize(self.insitu)

def main(args):
    if args.insitu:
        # run with in-situ Catalyst coupling
        sim = SimulationWithCatalyst(resolution=(args.res, args.res//2), iterations=args.timesteps, pv_script=args.script)
        sim.Initialize()
    else:
        sim = Simulation(resolution=(args.res, args.res//2), iterations=args.timesteps)

    sim.compute_loop()
    
    if args.matplotlib:
        sim.draw_matplotlib()

    if args.insitu:   
        sim.finalize_catalyst()

parser = argparse.ArgumentParser(
    description="Double Gyre miniapp for ParaView Catalyst")
parser.add_argument("-t", "--timesteps", type=int,
                    help="number of timesteps to run the miniapp (default: 1000)",
                    default=1000)
parser.add_argument("--res", type=int,
                    help="resolution along the X coordinate axis (default: 256)", default=256)
parser.add_argument("-s", "--script", type=str,
                    help="path to the Catalyst script to use for in situ processing.",
                    default="pvDoubleGyre.py")
parser.add_argument("-i", "--insitu",
                    help="toggle the use of the in-situ vis coupling with Catalyst",
                    action='store_true')  # on/off flag)
parser.add_argument("-m", "--matplotlib",
                    help="Use matplolib on final timestep",
                    action='store_true')  # on/off flag)

if __name__ == "__main__":
    args = parser.parse_args()
    main(args)
